name: My First CI

on:
  push:
  pull_request:

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v6

      - name: Check index.html
        run: test -f index.html
        
      - name: Explore runner
        run: |
          pwd
          ls
          echo "GitHub Actions is awesome!"