name: My First CI

on:
  push:
  pull_request:

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v6

      - name: Check index.html
        run: test -f index.html

      - name: Explore runner
        env:
            SEC_NEW: ${{ secrets.SEC_NEW }}
        run: |
          pwd
          ls -la
          echo "GitHub Actions is awesome!"
          if [ -n "$SEC_NEW" ]; then
            echo "Secret is available!"
          else
            echo "Secret is missing!"
            exit 1
          fi